from django.urls import path
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView
from .views import *

urlpatterns = [
    path('inicio_administrador/',InicioAdministrador.as_view(), name = 'inicio_administrador'),
    path('inicio_curso/',InicioCurso.as_view(), name = 'inicio_curso'),
    path('inicio_alumno/',InicioAlumno.as_view(), name = 'inicio_alumno'),
    path('inicio_carrera/',InicioCarrera.as_view(), name = 'inicio_carrera'),
    path('inicio_horario/',InicioHorario.as_view(), name = 'inicio_horario'),
    path('inicio_inscripcion/',InicioInscripcion.as_view(), name = 'inicio_inscripcion'),
    path('inicio_materia/',InicioMateria.as_view(), name = 'inicio_materia'),
    path('inicio_notas/',InicioNotas.as_view(), name = 'inicio_notas'),
    path('inicio_profesor/',InicioProfesor.as_view(), name = 'inicio_profesor'),
    path('crear_curso/',login_required(CrearCurso.as_view()), name = 'crear_curso'),
    path('crear_horario/',login_required(CrearHorario.as_view()), name = 'crear_horario'),
    path('crear_alumno/',login_required(CrearAlumno.as_view()), name = 'crear_alumno'),
    path('crear_inscripcion/',login_required(CrearInscripcion.as_view()), name = 'crear_inscripcion'),
    path('crear_administrador/',login_required(CrearAdministrador.as_view()), name = 'crear_administrador'),
    path('crear_profesor/',login_required(CrearProfesor.as_view()), name = 'crear_profesor'),
    path('crear_materia/',login_required(CrearMateria.as_view()), name = 'crear_materia'),
    path('crear_notas/',login_required(CrearNotas.as_view()), name = 'crear_notas'),
    path('crear_carrera/',login_required(CrearCarrera.as_view()), name = 'crear_carrera'),
    path('listar_cursos/',login_required(ListadoCursos.as_view()),name = 'listado_cursos'),
    path('listar_horarios/',login_required(ListadoHorarios.as_view()),name = 'listado_horarios'),
    path('listar_alumnos/',login_required(ListadoAlumnos.as_view()),name = 'listado_alumnos'),
    path('listar_inscripciones/',login_required(ListadoInscripciones.as_view()),name = 'listado_inscripciones'),
    path('listar_administradores/',login_required(ListadoAdministradores.as_view()),name = 'listado_administradores'),
    path('listar_profesores/',login_required(ListadoProfesores.as_view()),name = 'listado_profesores'),
    path('listar_materias/',login_required(ListadoMaterias.as_view()),name = 'listado_materias'),
    path('listar_notas/',login_required(ListadoNotas.as_view()),name = 'listado_notas'),
    path('listar_carreras/',login_required(ListadoCarreras.as_view()),name = 'listado_carreras'),
    path('editar_curso/<int:pk>/',login_required(ActualizarCurso.as_view()),name = 'editar_curso'),
    path('editar_horario/<int:pk>/',login_required(ActualizarHorario.as_view()),name = 'editar_horario'),
    path('editar_alumno/<int:pk>/',login_required(ActualizarAlumno.as_view()),name = 'editar_alumno'),
    path('editar_inscripcion/<int:pk>/',login_required(ActualizarInscripcion.as_view()),name = 'editar_inscripcion'),
    path('editar_administrador/<int:pk>/',login_required(ActualizarAdministrador.as_view()),name = 'editar_administrador'),
    path('editar_profesor/<int:pk>/',login_required(ActualizarProfesor.as_view()),name = 'editar_profesor'),
    path('editar_materia/<int:pk>/',login_required(ActualizarMateria.as_view()),name = 'editar_materia'),
    path('editar_notas/<int:pk>/',login_required(ActualizarNotas.as_view()),name = 'editar_notas'),
    path('editar_carrera/<int:pk>/',login_required(ActualizarCarrera.as_view()),name = 'editar_carrera'),
    path('eliminar_curso/<int:pk>/',login_required(EliminarCurso.as_view()),name = 'eliminar_curso'),
    path('eliminar_horario/<int:pk>/',login_required(EliminarHorario.as_view()),name = 'eliminar_horario'),
    path('eliminar_alumno/<int:pk>/',login_required(EliminarAlumno.as_view()),name = 'eliminar_alumno'),
    path('eliminar_inscripcion/<int:pk>/',login_required(EliminarInscripcion.as_view()),name = 'eliminar_inscripcion'),
    path('eliminar_administrador/<int:pk>/',login_required(EliminarAdministrador.as_view()),name = 'eliminar_administrador'),
    path('eliminar_profesor/<int:pk>/',login_required(EliminarProfesor.as_view()),name = 'eliminar_profesor'),
    path('eliminar_materia/<int:pk>/',login_required(EliminarMateria.as_view()),name = 'eliminar_materia'),
    path('eliminar_notas/<int:pk>/',login_required(EliminarNotas.as_view()),name = 'eliminar_notas'),
    path('eliminar_carrera/<int:pk>/',login_required(EliminarCarrera.as_view()),name = 'eliminar_carrera'),
    
    
]